[project]
name = "overayplugins"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "attrs>=25.3.0",
    "jinja2>=3.1.6",
    "json5>=0.12.1",
    "methodtools>=0.4.7",
    "psygnal>=0.15.1",
    "pycaw>=20240210",
    "pydantic>=2.11.7",
    "pyside6>=6.10.1",
    "pyyaml>=6.0.2",
    "toml>=0.10.2",
    "typer>=0.21.1",
]

[dependency-groups]
dev = [
    "overlay-sdk",
    "pyinstaller>=6.18.0",
    "taskipy>=1.14.1",
]

[tool.uv.sources]
overlay-sdk = { path = "wheel/overlay_sdk-1.0.0-py3-none-any.whl" }

[tool.taskipy.tasks]
build-tools = "pyinstaller scripts/OverlayTools.spec --noconfi"
