from fs.base import FS
from typing import Optional, Union, BinaryIO

class BinaryFileDescriptor:
    """
    Дескриптор бинарного файла с интерфейсом, аналогичным Python FileIO.
    """
    def __init__(self, filename: str, mode: str = 'rb', buffering: int = -1, **options) -> None: ...
    def write(self, data: Union[bytes, bytearray]) -> None: ...
    def read(self, size: int = -1) -> bytes: ...
    def close(self) -> None: ...
    def seek(self, pos: int, whence: int = 0) -> int: ...
    def tell(self) -> int: ...
    def flush(self) -> None: ...
    def truncate(self, size: Optional[int] = None) -> None: ...

class QrcFS(FS):
    """Файловая система для работы с Qt Resource System (qrc)"""
    def getinfo(self, path: str, namespaces=None) -> dict: ...
    def listdir(self, path: str) -> list[str]: ...
    def openbin(self, path: str, mode: str = "r", buffering: int = -1, **options) -> BinaryIO: ...

class QrcPathOpener:
    """Opener для qrc:// и qt:// протоколов"""
    protocols = ["qrc", "qt"]
    def getImplFS(self, url: str, parse_result, writable: bool, create: bool, cwd: str) -> FS: ...